'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Dedicacion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Dedicacion.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asignatura del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/dedAcumulada", ReplyAction:="*")>  _
        Function dedAcumulada(ByVal request As Dedicacion.dedAcumuladaRequest) As Dedicacion.dedAcumuladaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/dedAcumulada", ReplyAction:="*")>  _
        Function dedAcumuladaAsync(ByVal request As Dedicacion.dedAcumuladaRequest) As System.Threading.Tasks.Task(Of Dedicacion.dedAcumuladaResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class dedAcumuladaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="dedAcumulada", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Dedicacion.dedAcumuladaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Dedicacion.dedAcumuladaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class dedAcumuladaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public asignatura As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal asignatura As String)
            MyBase.New
            Me.asignatura = asignatura
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class dedAcumuladaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="dedAcumuladaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Dedicacion.dedAcumuladaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Dedicacion.dedAcumuladaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class dedAcumuladaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public dedAcumuladaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal dedAcumuladaResult As String)
            MyBase.New
            Me.dedAcumuladaResult = dedAcumuladaResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits Dedicacion.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of Dedicacion.WebService1Soap)
        Implements Dedicacion.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Dedicacion_WebService1Soap_dedAcumulada(ByVal request As Dedicacion.dedAcumuladaRequest) As Dedicacion.dedAcumuladaResponse Implements Dedicacion.WebService1Soap.dedAcumulada
            Return MyBase.Channel.dedAcumulada(request)
        End Function
        
        Public Function dedAcumulada(ByVal asignatura As String) As String
            Dim inValue As Dedicacion.dedAcumuladaRequest = New Dedicacion.dedAcumuladaRequest()
            inValue.Body = New Dedicacion.dedAcumuladaRequestBody()
            inValue.Body.asignatura = asignatura
            Dim retVal As Dedicacion.dedAcumuladaResponse = CType(Me,Dedicacion.WebService1Soap).dedAcumulada(inValue)
            Return retVal.Body.dedAcumuladaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Dedicacion_WebService1Soap_dedAcumuladaAsync(ByVal request As Dedicacion.dedAcumuladaRequest) As System.Threading.Tasks.Task(Of Dedicacion.dedAcumuladaResponse) Implements Dedicacion.WebService1Soap.dedAcumuladaAsync
            Return MyBase.Channel.dedAcumuladaAsync(request)
        End Function
        
        Public Function dedAcumuladaAsync(ByVal asignatura As String) As System.Threading.Tasks.Task(Of Dedicacion.dedAcumuladaResponse)
            Dim inValue As Dedicacion.dedAcumuladaRequest = New Dedicacion.dedAcumuladaRequest()
            inValue.Body = New Dedicacion.dedAcumuladaRequestBody()
            inValue.Body.asignatura = asignatura
            Return CType(Me,Dedicacion.WebService1Soap).dedAcumuladaAsync(inValue)
        End Function
    End Class
End Namespace
